version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dajo
      MYSQL_DATABASE: mydb
      MYSQL_USER: dajo_user
      MYSQL_PASSWORD: turnos_pass_dajo123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./server
    container_name: backend
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env.prod
    depends_on:
      - db
    restart: always

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
