# Imagen base oficial de Node
FROM node:18

# Crear carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias (sin las dev, más liviano)
RUN npm install --only=production

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto donde corre tu servidor
EXPOSE 3001

# Comando de inicio
CMD ["npm", "start"]
